
package com.sinosoft.ebusiness.rms.client.webservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "RmsClientService", targetNamespace = "http://facade.clientService.rms.ebusiness.sinosoft.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RmsClientService {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns com.sinosoft.ebusiness.rms.client.webservice.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://facade.clientService.rms.ebusiness.sinosoft.com/", className = "com.sinosoft.ebusiness.rms.client.webservice.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://facade.clientService.rms.ebusiness.sinosoft.com/", className = "com.sinosoft.ebusiness.rms.client.webservice.LoginResponse")
    public User login(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<com.sinosoft.ebusiness.rms.client.webservice.Company>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findCompanysByUserCodeAndPassword", targetNamespace = "http://facade.clientService.rms.ebusiness.sinosoft.com/", className = "com.sinosoft.ebusiness.rms.client.webservice.FindCompanysByUserCodeAndPassword")
    @ResponseWrapper(localName = "findCompanysByUserCodeAndPasswordResponse", targetNamespace = "http://facade.clientService.rms.ebusiness.sinosoft.com/", className = "com.sinosoft.ebusiness.rms.client.webservice.FindCompanysByUserCodeAndPasswordResponse")
    public List<Company> findCompanysByUserCodeAndPassword(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
