
package com.sinosoft.ebusiness.rms.client.cxf;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "RMSWebService", targetNamespace = "http://facade.webService.service.rms.ebusiness.sinosoft.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RMSWebService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "webServiceSelectCom", targetNamespace = "http://facade.webService.service.rms.ebusiness.sinosoft.com/", className = "com.sinosoft.ebusiness.rms.client.cxf.WebServiceSelectCom")
    @ResponseWrapper(localName = "webServiceSelectComResponse", targetNamespace = "http://facade.webService.service.rms.ebusiness.sinosoft.com/", className = "com.sinosoft.ebusiness.rms.client.cxf.WebServiceSelectComResponse")
    public List<String> webServiceSelectCom(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns com.sinosoft.ebusiness.rms.client.cxf.WebServiceDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "webServiceLogin", targetNamespace = "http://facade.webService.service.rms.ebusiness.sinosoft.com/", className = "com.sinosoft.ebusiness.rms.client.cxf.WebServiceLogin")
    @ResponseWrapper(localName = "webServiceLoginResponse", targetNamespace = "http://facade.webService.service.rms.ebusiness.sinosoft.com/", className = "com.sinosoft.ebusiness.rms.client.cxf.WebServiceLoginResponse")
    public WebServiceDTO webServiceLogin(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

}
